os: linux
dist: trusty
language: go

services:
  - rabbitmq

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

script:
  - go get ./...
  - go mod graph
  - gofmt -d -s .
  - go vet *.go
  - go test -v -race -mock-broker=1 # Run tests with real broker.
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -mock-broker=0 # Run tests with fake broker and collect coverage.

after_success:
  - bash <(curl -s https://codecov.io/bash)
